import { rem } from "nativewind";

export const Strings = {
    login:{
        title: 'ĐĂNG NHẬP',
        username: 'Tên đăng nhập',
        password: 'Mật khẩu',
        login: 'Đăng nhập',
        forgotPassword: 'Quên mật khẩu?',
        register: 'Đăng ký',
        loggingin: 'Đang đăng nhập...',  
        dontHaveAccount: 'Chưa có tài khoản?',
        loginSuccess: 'Đăng nhập thành công',
        loginFailed: 'Đăng nhập thất bại',
        signInByGoogle: 'Đăng nhập bằng Google',
        rememberMe: 'Lưu tài khoản',
        placeHolderUsername: 'Nhập tên đăng nhập',
        placeHolderPassword: 'Nhập mật khẩu',
    },

    register:{
        title: 'ĐĂNG KÝ',
        descripton: 'Tham gia nền tảng quản lý khóa học trực tuyến',
        username: 'Tên đăng nhập',
        email: 'Email',
        password: 'Mật khẩu',
        confirmPassword: 'Nhập lại mật khẩu',
        register: 'Đăng ký',
        registerProcess: 'Đang xử lý...',
        registerSuccess: 'Đăng ký thành công',
        registerFailed: 'Đăng ký thất bại',
        alreadyHaveAccount: 'Đã có tài khoản?',
        signIn: 'Đăng nhập',
        requireFullname: 'Nhập họ và tên',
        requireUsername: 'Nhập tên đăng nhập',
        requireEmail: 'Nhập email',
        requirePassword: 'Nhập mật khẩu',
        passwordNotMatch: 'Mật khẩu không khớp',
        invalidEmail: 'Email không hợp lệ',
        minimumPassword: 'Mật khẩu phải có ít nhất 6 ký tự',
        invalidUsername: 'Tên đăng nhập không hợp lệ',
        invalidPassword: 'Mật khẩu không hợp lệ',
        placeHolderFullname: 'Nhập họ và tên',
        placeHolderUsername: 'Nhập tên đăng nhập',
        placeHolderEmail: 'Nhập email',
        placeHolderPassword: 'Nhập mật khẩu',
        placeHolderConfirmPassword: 'Nhập lại mật khẩu',
    },
    user_home:{
        welcome_back: 'Chào mừng trở lại',
        continue_learning: 'Tiếp tục khóa học',
        popular_courses: 'Khóa học phổ biến',
        view_all: 'Xem tất cả',
        suggest_courses: 'Gợi ý cho bạn',
        no_enrolled_courses: 'Bạn chưa tham gia khóa học nào',
        complete: 'Hoàn thành',
        last_accessed:"Lần truy cập gần nhất",
        loading_your_courses: 'Đang tải khóa học...',
    },

    categories: {
        title: 'DANH SÁCH CHỦ ĐỀ',
        loading: 'Đang tải chủ đề',
        confirmDelete: 'Xác nhận xóa chủ đề',
        questionConfirmDelete: 'Bạn có chắc muốn xóa chủ đề có tên ',
        warningConfirmDelete: 'Hành động này sẽ xóa luôn tất cả khóa học có chủ đề này.',
        cancelButton: "Hủy",
        deleteButton: "Xóa",
        searchPlaceholder: "Tìm kiếm chủ đề...",
        deleteSuccess: "Xóa chủ đề thành công",
        deleteError: "Không thể xóa chủ đề",
        addNew: "Thêm mới chủ đề",
        update: "Cập nhật chủ đề",
        nameLabel: "Nhập tên chủ đề:",
        descriptionLabel: "Mô tả chủ đề:",
        idLabel: "ID chủ đề:",
        saveButton: "Lưu",
        resetButton: "Reset",
        processing: "Đang xử lý...",
        nameRequired: "Vui lòng nhập tên chủ đề",
        addSuccess: "Thêm chủ đề thành công mã",
        addError: "Không thể thêm chủ đề. Vui lòng thử lại sau.",
        updateSuccess: "Cập nhật chủ đề thành công",
        updateError: "Dữ liệu không hợp lệ",
        loadError: "Không thể tải thông tin chủ đề",
        resetError: "Không thể khôi phục dữ liệu",
    },
    
    courses: {
        title: 'DANH SÁCH KHÓA HỌC',
        loading: 'Đang tải khóa học',
        confirmDelete: 'Xác nhận xóa khóa học',
        questionConfirmDelete: 'Bạn có chắc muốn xóa khóa học có tên ',
        warningConfirmDelete: 'Hành động này sẽ xóa luôn tất cả mục lục khóa học, đánh giá và bình luận của khóa học này.',
        cancelButton: "Hủy",
        deleteButton: "Xóa",
        searchPlaceholder: "Tìm kiếm khóa học...",
        deleteSuccess: "Xóa khóa học thành công",
        deleteError: "Không thể xóa khóa học",
        addNew: "Thêm mới khóa học",
        update: "Cập nhật khóa học",
        nameLabel: "Nhập tên khóa học:",
        descriptionLabel: "Mô tả khóa học:",
        idLabel: "ID khóa học:",
        saveButton: "Lưu",
        resetButton: "Reset",
        processing: "Đang xử lý...",
        nameRequired: "Vui lòng nhập tên khóa học",
        categoryRequired: "Vui lòng chọn chủ đề cho khóa học",
        addSuccess: "Khóa học đã được tạo",
        addError: "Không thể thêm khóa học. Vui lòng thử lại sau.",
        updateSuccess: "Cập nhật khóa học thành công",
        updateError: "Dữ liệu không hợp lệ",
        loadError: "Không thể tải thông tin khóa học",
        resetError: "Không thể khôi phục dữ liệu",
        uploadError: "Không thể upload ảnh lên cloud",
        pickImageError: "Có lỗi xảy ra khi chọn ảnh",
    },
}