import { rem } from "nativewind";

export const Strings = {
    login:{
        title: 'ĐĂNG NHẬP',
        username: 'Tên đăng nhập',
        password: 'Mật khẩu',
        login: 'Đăng nhập',
        forgotPassword: 'Quên mật khẩu?',
        register: 'Đăng ký',
        dontHaveAccount: 'Chưa có tài khoản?',
        loginSuccess: 'Đăng nhập thành công',
        loginFailed: 'Đăng nhập thất bại',
        rememberMe: 'Lưu tài khoản',
        placeHolderUsername: 'Nhập tên đăng nhập',
        placeHolderPassword: 'Nhập mật khẩu',
    },


    categories: {
        title: 'DANH SÁCH CHỦ ĐỀ',
        loading: 'Đang tải chủ đề',
        confirmDelete: 'Xác nhận xóa chủ đề',
        questionConfirmDelete: 'Bạn có chắc muốn xóa chủ đề có tên ',
        warningConfirmDelete: 'Hành động này sẽ xóa luôn tất cả khóa học có chủ đề này.',
        cancelButton: "Hủy",
        deleteButton: "Xóa",
        searchPlaceholder: "Tìm kiếm danh mục...",
        deleteSuccess: "Xóa danh mục thành công",
        deleteError: "Không thể xóa danh mục",
        addNew: "Thêm mới chủ đề",
        update: "Cập nhật chủ đề",
        nameLabel: "Nhập tên danh mục:",
        descriptionLabel: "Mô tả danh mục:",
        idLabel: "ID danh mục:",
        saveButton: "Lưu",
        resetButton: "Reset",
        processing: "Đang xử lý...",
        nameRequired: "Vui lòng nhập tên danh mục",
        addSuccess: "Thêm danh mục thành công",
        addError: "Không thể thêm danh mục. Vui lòng thử lại sau.",
        updateSuccess: "Cập nhật danh mục thành công",
        updateError: "Dữ liệu không hợp lệ",
        loadError: "Không thể tải thông tin danh mục",
        resetError: "Không thể khôi phục dữ liệu",
    },
}