import { rem } from "nativewind";

export const Strings = {
    login:{
        title: 'ĐĂNG NHẬP',
        username: 'Tên đăng nhập',
        password: 'Mật khẩu',
        login: 'Đăng nhập',
        forgotPassword: 'Quên mật khẩu?',
        register: 'Đăng ký',
        loggingin: 'Đang đăng nhập...',  
        dontHaveAccount: 'Chưa có tài khoản?',
        loginSuccess: 'Đăng nhập thành công',
        loginFailed: 'Đăng nhập thất bại',
        signInByGoogle: 'Đăng nhập bằng Google',
        rememberMe: 'Lưu tài khoản',
        placeHolderUsername: 'Nhập tên đăng nhập',
        placeHolderPassword: 'Nhập mật khẩu',

    },
    register:{
        title: 'ĐĂNG KÝ',
        descripton: 'Tham gia nền tảng quản lý khóa học trực tuyến',
        username: 'Tên đăng nhập',
        email: 'Email',
        password: 'Mật khẩu',
        confirmPassword: 'Nhập lại mật khẩu',
        register: 'Đăng ký',
        registerProcess: 'Đang xử lý...',
        registerSuccess: 'Đăng ký thành công',
        registerFailed: 'Đăng ký thất bại',
        alreadyHaveAccount: 'Đã có tài khoản?',
        signIn: 'Đăng nhập',
        requireFullname: 'Nhập họ và tên',
        requireUsername: 'Nhập tên đăng nhập',
        requireEmail: 'Nhập email',
        requirePassword: 'Nhập mật khẩu',
        passwordNotMatch: 'Mật khẩu không khớp',
        invalidEmail: 'Email không hợp lệ',
        minimumPassword: 'Mật khẩu phải có ít nhất 6 ký tự',
        invalidUsername: 'Tên đăng nhập không hợp lệ',
        invalidPassword: 'Mật khẩu không hợp lệ',
        placeHolderFullname: 'Nhập họ và tên',
        placeHolderUsername: 'Nhập tên đăng nhập',
        placeHolderEmail: 'Nhập email',
        placeHolderPassword: 'Nhập mật khẩu',
        placeHolderConfirmPassword: 'Nhập lại mật khẩu',
    },

}